<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<title>STUDENT LEDGER</title>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 9">
<meta name=Originator content="Microsoft Word 9">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>James Dizon</o:Author>
  <o:Template>Normal</o:Template>
  <o:LastAuthor>James Dizon</o:LastAuthor>
  <o:Revision>2</o:Revision>
  <o:TotalTime>26</o:TotalTime>
  <o:Created>2007-04-23T23:46:00Z</o:Created>
  <o:LastSaved>2007-04-24T00:12:00Z</o:LastSaved>
  <o:Pages>1</o:Pages>
  <o:Company>AUF</o:Company>
  <o:Lines>1</o:Lines>
  <o:Paragraphs>1</o:Paragraphs>
  <o:Version>9.2720</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<!--[if gte mso 9]><xml>
 <w:WordDocument>
  <w:View>Print</w:View>
 </w:WordDocument>
</xml><![endif]-->
<style>
<!--
 /* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{
	margin:0in;
	margin-bottom:.0001pt;
	font-size:12.0pt;
	font-family:"Times New Roman";}
h1
	{
	margin:0in;
	margin-bottom:.0001pt;
	text-align:center;
	page-break-after:avoid;
	font-size:10.0pt;
	font-family:"Times New Roman";}

/** My code below.. code above is generated by word - given by AUF **/
.nav {
     color: #000000;
     background-color: #FFFFFF;
}
.nav-highlight {
     color: #000000;
     background-color: #0099FF;
}

-->
</style>
</head>
<script src="../../../jscript/td.js"></script>
<script language="javascript">
function navRollOver(obj, state) {
  document.getElementById(obj).className = (state == 'on') ? 'nav-highlight' : 'nav';
}

function printRow(rowID) {
	if(document.form_.print_clicked.value == "1") {
		this.showAll();
		document.form_.print_clicked.value = "";
		return;
	}
	document.form_.print_clicked.value = "1";
	var rowIDName = "";
	var iMaxRow = eval(document.form_.max_rows.value);

	if(rowID < 11) {///print all upto tuition fee. 
		for(var i = 11; i <= iMaxRow; ++i) {
			rowIDName = 'row_'+i;
			//else hide rows.
			if(document.getElementById(rowIDName))
				hideLayer(rowIDName);	
		}
		window.print();
		return;
	}
	for(var i = 1; i <= iMaxRow; ++i) {
		if(i == rowID)
			continue;
		//else hide rows.
		rowIDName = 'row_'+i;
		if(document.getElementById(rowIDName))
			hideLayer(rowIDName);
	}

	window.print();
}
function showAll() {
	var iMaxRow = eval(document.form_.max_rows.value);
	for(var i = 1; i <= iMaxRow; ++i) {
		rowIDName = 'row_'+i;
		//else hide rows.
		if(document.getElementById(rowIDName))
			showLayer(rowIDName);	
	}
}
</script>

<%@ page language="java" import="utility.*,enrollment.FAPaymentUtil,enrollment.FAStudentLedger,enrollment.EnrlAddDropSubject,java.util.Vector,java.util.Date" %>
<%
	DBOperation dbOP = null;
	WebInterface WI = new WebInterface(request);

//forward the page here.
if(WI.fillTextValue("show_all").compareTo("1") ==0){
	response.sendRedirect("./student_ledger_viewall.jsp?stud_id="+WI.fillTextValue("id_in_url"));
	return;
}

	String strErrMsg = null;
	String strTemp = null;String strTemp2 = null;
	String[] astrConvertTerm = {"Summer","1st Semester","2nd Semester","3rd Semester"};

	boolean bolProceed = true;
//add security here.
	try
	{
		dbOP = new DBOperation((String)request.getSession(false).getAttribute("userId"),
								"Admin/staff-Fee Assessment & Payments-Student ledger","student_ledger.jsp");
	}
	catch(Exception exp)
	{
		exp.printStackTrace();
		%>
		<p align="center"> <font face="Verdana, Arial, Helvetica, sans-serif" size="3">
		Error in opening connection</font></p>
		<%
		return;
	}
//authenticate this user.
CommonUtil comUtil = new CommonUtil();
int iAccessLevel = comUtil.isUserAuthorizedForURL(dbOP,(String)request.getSession(false).getAttribute("userId"),
														"Fee Assessment & Payments","STUDENT LEDGER",request.getRemoteAddr(),
														"student_ledger.jsp");
if(iAccessLevel == -1)//for fatal error.
{
	dbOP.cleanUP();
	request.getSession(false).setAttribute("go_home","../ADMIN_STAFF/main%20files/admin_staff_home_button_content.htm");
	request.getSession(false).setAttribute("errorMessage",comUtil.getErrMsg());
	response.sendRedirect("../../../commfile/fatal_error.jsp");
	return;
}
else if(iAccessLevel == 0)//NOT AUTHORIZED.
{
	dbOP.cleanUP();
	response.sendRedirect("../../../commfile/unauthorized_page.jsp");
	return;
}

//end of authenticaion code.


Vector vBasicInfo = null;
Vector vLedgerInfo = null;

Vector vTimeSch = null;
Vector vAdjustment = null;
Vector vRefund = null;
Vector vDorm = null;
Vector vOthSchFine = null;
Vector vPayment = null;
Vector vAddedSub = null;
Vector vDroppedSub = null;



Vector vTuitionFeeDetail = null;


FAPaymentUtil paymentUtil = new FAPaymentUtil();
FAStudentLedger faStudLedg = new FAStudentLedger();
EnrlAddDropSubject eADS = new EnrlAddDropSubject();

if(WI.fillTextValue("stud_id").length() > 0)
{
	vBasicInfo = paymentUtil.getStudBasicInfoOLD(dbOP, request.getParameter("stud_id"),
	request.getParameter("sy_from"),request.getParameter("sy_to"),request.getParameter("semester"));
	if(vBasicInfo == null)
		vBasicInfo = paymentUtil.getStudBasicInfoOLD(dbOP, request.getParameter("stud_id"));
	if(vBasicInfo == null) //may be it is the teacher/staff
		strErrMsg = paymentUtil.getErrMsg();
	else//check if this student is called for old ledger information.
	{
		int iDisplayType = faStudLedg.isOldLedgerInformation(dbOP, (String)vBasicInfo.elementAt(0),request.getParameter("sy_from"),
											request.getParameter("sy_to"),request.getParameter("semester"));
		if(iDisplayType ==-1) //Error.
		{
			%>
			<p align="center"> <font face="Verdana, Arial, Helvetica, sans-serif" size="3"><%=faStudLedg.getErrMsg()%></font></p>
			<%
			dbOP.cleanUP();
			return;
		}
		if(iDisplayType ==1)//this is called for old ledger information.
		{
			dbOP.cleanUP();
			response.sendRedirect(response.encodeRedirectURL("./old_student_ledger_view.jsp?stud_id="+request.getParameter("stud_id")+"&sy_from="+
				request.getParameter("sy_from")+"&sy_to="+request.getParameter("sy_to")+"&semester="+request.getParameter("semester")));
			return;
		}
	}
	//check if the applicant is having reservation already, if so - take directly to the print page,
	if(vBasicInfo != null && vBasicInfo.size() > 0)
	{//long lTime = new java.util.Date().getTime();
		boolean bolShowOnlyDroppedSub = false;
		if(WI.fillTextValue("show_dropped_only").length() > 0)
			bolShowOnlyDroppedSub = true;
		vLedgerInfo = faStudLedg.viewLedgerTuition(dbOP, (String)vBasicInfo.elementAt(0),request.getParameter("sy_from"),
			request.getParameter("sy_to"),null,request.getParameter("semester"), bolShowOnlyDroppedSub);
		if(vLedgerInfo == null)
			strErrMsg = faStudLedg.getErrMsg();
		else
		{//System.out.println( (new java.util.Date().getTime() - lTime)/1000);
			vTimeSch 			= (Vector)vLedgerInfo.elementAt(0);
			vTuitionFeeDetail	= (Vector)vLedgerInfo.elementAt(1);
			vAdjustment			= (Vector)vLedgerInfo.elementAt(2);
			vRefund				= (Vector)vLedgerInfo.elementAt(3);
			vDorm 				= (Vector)vLedgerInfo.elementAt(4);
			vOthSchFine			= (Vector)vLedgerInfo.elementAt(5);//System.out.println(vOthSchFine);
			vPayment			= (Vector)vLedgerInfo.elementAt(6);
			if(vTimeSch == null || vTimeSch.size() ==0)
				strErrMsg = faStudLedg.getErrMsg();
		}

	}
}
else
	strErrMsg = "Please enter student ID";

//System.out.println(vDroppedSub);
dbOP.cleanUP();

int iIndexOf = 0;

boolean bolShowLabel = false;
//startLine.. 
int iStartLine = Integer.parseInt(WI.getStrValue(WI.fillTextValue("start_line"),"0"));

%>
<body <%if(strErrMsg == null && false){%> onLoad="window.print();"<%}//no printing on load.%>>

<%if(strErrMsg != null) {%>
<p style="font-size:16px; color:#FF0000; font-weight:bold; font-family:Verdana, Arial, Helvetica, sans-serif"><%=strErrMsg%></p>
<%return;}%>
<form name="form_">

<table cellpadding="0" cellspacing="0">
<%for(int i = 0;i < iStartLine; ++i) {%>
	<tr><td height="20">&nbsp;</td></tr>
<%}%>
</table>

  <table border=0 cellspacing=0 cellpadding=0 width=603 style='width:361.6pt; border-collapse:collapse;'>
<%if(iStartLine == 0) {//show only if it is start of ledger..%>
    <tr id="row_1">
      <td width=334 colspan=4 valign=top style='width:200.25pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:left; font-size:12px;'>
	  <%=(String)vBasicInfo.elementAt(1)%></p></td>
      <td width=48 colspan=2 valign=top style='width:28.6pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center'>
          <![if !supportEmptyParas]>
&nbsp;
          <![endif]>
          <o:p></o:p></p></td>
      <td width=221 colspan=3 valign=top style='width:132.75pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center; font-size:12px;'>
	  <%=request.getParameter("stud_id")%>
	  </p></td>
    </tr>
    <tr>
      <td width=334 colspan=4 valign=top style='width:200.25pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center'><span
  style='font-size:8.0pt;'><%if(bolShowLabel){%>NAME<%}%>&nbsp;<o:p></o:p></span></p></td>
      <td width=48 colspan=2 valign=top style='width:28.6pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center'>
          <![if !supportEmptyParas]>
&nbsp;
          <![endif]>
          <o:p></o:p></p></td>
      <td width=221 colspan=3 valign=top style='width:132.75pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center'><span
  style='font-size:8.0pt;'><%if(bolShowLabel){%>STUDENT NUMBER<%}%>&nbsp;<o:p></o:p></span></p></td>
    </tr>
    <tr id="row_2">
      <td width=334 colspan=4 valign=top style='width:200.25pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:left; font-size:12px;'>
	  
	  <%
	  strTemp = (String)vBasicInfo.elementAt(14);
	  String strAddrLine2 = null;String strAddrLine1 = strTemp;
	  if(strTemp != null && strTemp.length() > 50) {
	  	iIndexOf = strTemp.indexOf(" ", 35);
		if(iIndexOf == -1)
			iIndexOf = strTemp.indexOf(",",35);
		if(iIndexOf > -1) {
	  		strAddrLine1 = strTemp.substring(0,iIndexOf);
			strAddrLine2 = strTemp.substring(iIndexOf + 1);
		}
	  }%>
	  <%=WI.getStrValue(strAddrLine1)%>
	  </p></td>
      <td width=48 colspan=2 valign=top style='width:28.6pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center'>
          <![if !supportEmptyParas]>
&nbsp;
          <![endif]>
          <o:p></o:p></p></td>
      <td width=221 colspan=3 valign=top style='width:132.75pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center; font-size:12px;'>
	  <%=(String)vBasicInfo.elementAt(2)%>
	  </p></td>
    </tr>
    <tr>
      <td width=334 colspan=4 valign=top style='width:200.25pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center'><span
  style='font-size:8.0pt;'><%if(bolShowLabel){%>ADDRESS<%}%><o:p></o:p></span></p></td>
      <td width=48 colspan=2 valign=top style='width:28.6pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center'>
          <![if !supportEmptyParas]>
&nbsp;
          <![endif]>
          <o:p></o:p></p></td>
      <td width=221 colspan=3 valign=top style='width:132.75pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center'><span
  style='font-size:8.0pt;'><%if(bolShowLabel){%>COURSE<%}%><o:p></o:p></span></p></td>
    </tr>
    <tr id="row_3">
      <td width=334 colspan=4 valign=top style='width:200.25pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:left; font-size:12px'>
	  <%if(strAddrLine2 != null){%><%=strAddrLine2%><%}%>
	  </p></td>
      <td width=48 colspan=2 valign=top style='width:28.6pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center'>
          <![if !supportEmptyParas]>
&nbsp;
          <![endif]>
          <o:p></o:p></p></td>
      <td width=221 colspan=3 valign=top style='width:132.75pt;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:left; font-size:12px'>
	<%=astrConvertTerm[Integer.parseInt((String)vBasicInfo.elementAt(5))]%>, <%=WI.fillTextValue("sy_from")%> <%=WI.fillTextValue("sy_to")%>
		</p></td>
    </tr>
    <tr>
      <td colspan=9 valign=top style='width:361.6pt;padding:0in 5.4pt 0in 5.4pt'><h1><%if(bolShowLabel){%>STUDENT LEDGER<%}%>&nbsp;</h1></td>
    </tr>
    <tr>
      <td width=69 valign=top style='width:41.4pt;
  padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal>
          <![if !supportEmptyParas]>
&nbsp;
          <![endif]>
          <span
  style='font-size:8.0pt;'><o:p></o:p></span></p></td>
      <td width=95 valign=top style='width:56.95pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal><b><span style='font-size:7.0pt;'><%if(bolShowLabel){%>DATE<%}%>&nbsp;<o:p></o:p></span></b></p></td>
      <td width=108 valign=top style='width:64.9pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal><b><span style='font-size:7.0pt;'><%if(bolShowLabel){%>REFERENCE<%}%>&nbsp;<o:p></o:p></span></b></p></td>
      <td width=80 colspan=2 valign=top style='width:48.15pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal><b><span style='font-size:7.0pt;'><%if(bolShowLabel){%>CHARGES<%}%>&nbsp;<o:p></o:p></span></b></p></td>
      <td width=90 colspan=2 valign=top style='width:53.95pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal><b><span style='font-size:7.0pt;'><%if(bolShowLabel){%>PAYMENTS<%}%>&nbsp;<o:p></o:p></span></b></p></td>
      <td width=82 valign=top style='width:49.3pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal><b><span style='font-size:7.0pt;'><%if(bolShowLabel){%>BALANCE<%}%>&nbsp;<o:p></o:p></span></b></p></td>
      <td width=78 valign=top style='width:46.95pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal><b><span style='font-size:7.0pt;'><%if(bolShowLabel){%>ACCTG<br>CLERK<%}else{%>&nbsp;<br>&nbsp;<%}%><o:p></o:p></span></b></p></td>
    </tr>

<%}//do not show if start line number is > 0

//start of loop.. 
int iRunningLineNo = 10;
if(vTimeSch != null && vTimeSch.size() > 0){
	float fBalance = ((Float)vTuitionFeeDetail.elementAt(0)).floatValue();
	float fCredit = 0;
	float fDebit = 0;
	String strTransDate = null;
	int iIndex = 0;
	
	int iLineNumber = 1;

if(iStartLine > 0){%>

    <tr id="row_4">
		<td colspan="9" style="font-size:12px; font-family: 'Times New Roman', Times, serif">&nbsp;&nbsp;
<%=astrConvertTerm[Integer.parseInt((String)vBasicInfo.elementAt(5))]%>, <%=WI.fillTextValue("sy_from")%> <%=WI.fillTextValue("sy_to")%>			
		</td>
        <!--
      <td colspan=3 valign=top style='width:163.25pt; border-top:none;padding:0in 5.4pt 0in 5.4pt'>&nbsp;</td>
      <td colspan=2 valign=top style='width:48.15pt; padding:0in 5.4pt 0in 5.4pt'>&nbsp;</td>
      <td colspan=3 align="right" style="font-size:12px;">&nbsp;</td>
      <td  align="right" style="font-size:12px;">&nbsp;</td>
-->
    </tr>
<%}%>
    <tr id="row_4">
      <td width=272 colspan=3 valign=top style='width:163.25pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal align=center style='text-align:center'><span
  style='font-size:8.0pt;'><%if(iStartLine > 0){%>BALANCE FORWARDED<%}%>&nbsp;<o:p></o:p></span></p></td>
      <td width=80 colspan=2 valign=top style='width:48.15pt; padding:0in 5.4pt 0in 5.4pt'><p class=MsoNormal>
          <![if !supportEmptyParas]>
&nbsp;
          <![endif]>
          <span
  style='font-size:8.0pt;'><o:p></o:p></span></p></td>
      <td colspan=3 align="right" style="font-size:12px;"><%=CommonUtil.formatFloat(fBalance,true)%></td>
      <td  align="right" style="font-size:12px;">&nbsp;</td>
    </tr>
<%
for(int i=0; i<vTimeSch.size(); ++i){
	strTransDate = ConversionTable.convertMMDDYYYY((Date)vTimeSch.elementAt(i));
	
	if(vTuitionFeeDetail.contains((Date)vTimeSch.elementAt(i))){
		fDebit = ((Float)vTuitionFeeDetail.elementAt(1)).floatValue();
		fBalance += fDebit;
%>
   <tr id="row_5">
      <td width=69 align="right" style="font-size:12px"><%if(bolShowLabel){%><%=iLineNumber++%><%}%> &nbsp;&nbsp;</td>
      <td width=95 valign=top style="font-size:12px;"><%=strTransDate%></td>
      <td width=108 valign=top style="font-size:12px;">TF</td>
      <td width=80 colspan=2 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fDebit,true)%></td>
      <td width=90 colspan=2 valign="top" style="font-size:12px;"></td>
      <td width=82 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fBalance,true)%></td>
      <td width=78 valign="top" style="font-size:12px;"></td>
    </tr>
<%
	fDebit = ((Float)vTuitionFeeDetail.elementAt(2)).floatValue();
	fBalance += fDebit;
%>
   <tr id="row_6" onClick="printRow(6);" class="nav" onMouseOver="navRollOver('row_6', 'on')" onMouseOut="navRollOver('row_6', 'off')">
      <td width=69 align="right" style="font-size:12px"><%if(bolShowLabel){%><%=iLineNumber++%><%}%> &nbsp;&nbsp;</td>
      <td width=95 valign=top style="font-size:12px;"><%=strTransDate%></td>
      <td width=108 valign=top style="font-size:12px;">MISC</td>
      <td width=80 colspan=2 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fDebit,true)%></td>
      <td width=90 colspan=2 valign="top" style="font-size:12px;"></td>
      <td width=82 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fBalance,true)%></td>
      <td width=78 valign="top" style="font-size:12px;"></td>
    </tr>
<%
fDebit = ((Float)vTuitionFeeDetail.elementAt(7)).floatValue();
if(fDebit > 0f){
	fBalance += fDebit;%>

   <tr id="row_7" onClick="printRow(7);" class="nav" onMouseOver="navRollOver('row_7', 'on')" onMouseOut="navRollOver('row_7', 'off')">
      <td width=69 align="right" style="font-size:12px"><%if(bolShowLabel){%><%=iLineNumber++%><%}%> &nbsp;&nbsp;</td>
      <td width=95 valign=top style="font-size:12px;"><%=strTransDate%></td>
      <td width=108 valign=top style="font-size:12px;">OC</td>
      <td width=80 colspan=2 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fDebit,true)%></td>
      <td width=90 colspan=2 valign="top" style="font-size:12px;"></td>
      <td width=82 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fBalance,true)%></td>
      <td width=78 valign="top" style="font-size:12px;"></td>
    </tr>
    <%}
fDebit = ((Float)vTuitionFeeDetail.elementAt(3)).floatValue();
if(fDebit > 0f){
	fBalance += fDebit;%>
   <tr id="row_8" onClick="printRow(8);" class="nav" onMouseOver="navRollOver('row_8', 'on')" onMouseOut="navRollOver('row_8', 'off')">
      <td width=69 align="right" style="font-size:12px"><%if(bolShowLabel){%><%=iLineNumber++%><%}%>&nbsp;&nbsp;</td>
      <td width=95 valign=top style="font-size:12px;"><%=strTransDate%></td>
      <td width=108 valign=top style="font-size:12px;">Hands on</td>
      <td width=80 colspan=2 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fDebit,true)%></td>
      <td width=90 colspan=2 valign="top" style="font-size:12px;"></td>
      <td width=82 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fBalance,true)%></td>
      <td width=78 valign="top" style="font-size:12px;"></td>
    </tr>
    <%}
//show this if there is any discounts.
if(vTuitionFeeDetail.elementAt(5) != null){
	float fTemp = ((Float)vTuitionFeeDetail.elementAt(5)).floatValue();
	if(fTemp > 0)
		fCredit = fTemp;
	else
		fDebit  =  -1 * fTemp;
	fBalance -= fTemp;
	
	strTemp  = (String)vTuitionFeeDetail.elementAt(6);
	//System.out.println(strTemp);
	if(strTemp.trim().startsWith("Full payment discount"))
		strTemp = "Full pmt Disc";
		

	%>
   <tr id="row_9" onClick="printRow(9);" class="nav" onMouseOver="navRollOver('row_9', 'on')" onMouseOut="navRollOver('row_9', 'off')">
      <td width=69 align="right" style="font-size:12px"><%if(bolShowLabel){%><%=iLineNumber++%><%}%> &nbsp;&nbsp;</td>
      <td width=95 valign=top style="font-size:12px;"><%=strTransDate%></td>
      <td width=108 valign=top style="font-size:12px;"><%=strTemp%></td>
      <td width=80 colspan=2 valign="top" style="font-size:12px;" align="right">&nbsp; <%if(fDebit > 0f){%> <%=CommonUtil.formatFloat(fDebit,true)%> <%}%> </td>
      <td width=90 colspan=2 valign="top" align="right" style="font-size:12px;">&nbsp; <%if(fCredit > 0f){%> <%=CommonUtil.formatFloat(fCredit,true)%> <%}%> </td>
      <td width=82 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fBalance,true)%></td>
      <td width=78 valign="top" style="font-size:12px;">&nbsp;</td>
    </tr>
  <%}if(vTuitionFeeDetail.elementAt(8) != null){%>
   <tr id="row_10" onClick="printRow(10);" class="nav" onMouseOver="navRollOver('row_10', 'on')" onMouseOut="navRollOver('row_10', 'off')">
      <td width=69 align="right" style="font-size:12px"><%if(bolShowLabel){%><%=iLineNumber++%><%}%> &nbsp;&nbsp;</td>
      <td colspan=8 valign="top" style="font-size:12px;">NOTE : <%=(String)vTuitionFeeDetail.elementAt(8)%></td>
    </tr>
    <%
	}
} //if(vTuitionFeeDetail.contains((Date)vTimeSch.elementAt(i))){.

//adjustment here
//System.out.println(vAdjustment);
while( (iIndex = vAdjustment.indexOf((Date)vTimeSch.elementAt(i))) != -1) {
	fCredit = Float.parseFloat((String)vAdjustment.elementAt(iIndex-3));
	fBalance -= fCredit;
%>
   <tr id="row_<%=++iRunningLineNo%>" onClick="printRow(<%=iRunningLineNo%>);" class="nav" onMouseOver="navRollOver('row_<%=iRunningLineNo%>', 'on')" onMouseOut="navRollOver('row_<%=iRunningLineNo%>', 'off')">
      <td width=69 align="right" style="font-size:12px"><%if(bolShowLabel){%><%=iLineNumber++%><%}%> &nbsp;&nbsp;</td>
      <td width=95 valign=top style="font-size:12px;"><%=strTransDate%></td>
      <td width=108 valign=top style="font-size:12px;">DISC</td>
      <td width=80 colspan=2 valign="top" style="font-size:12px;" align="right">&nbsp;</td>
      <td width=90 colspan=2 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fCredit,true)%> </td>
      <td width=82 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fBalance,true)%></td>
      <td width=78 valign="top" style="font-size:12px;">&nbsp;</td>
    </tr>
    <%
	//remove the element here.
	vAdjustment.removeElementAt(iIndex);vAdjustment.removeElementAt(iIndex-1);vAdjustment.removeElementAt(iIndex-2);
	vAdjustment.removeElementAt(iIndex-3);vAdjustment.removeElementAt(iIndex-4);
}

//Refund here
while( (iIndex = vRefund.indexOf((Date)vTimeSch.elementAt(i))) != -1) {
	fDebit = Float.parseFloat((String)vRefund.elementAt(iIndex-1));
	fBalance += fDebit;
%>
   <tr id="row_<%=++iRunningLineNo%>" onClick="printRow(<%=iRunningLineNo%>);" class="nav" onMouseOver="navRollOver('row_<%=iRunningLineNo%>', 'on')" onMouseOut="navRollOver('row_<%=iRunningLineNo%>', 'off')">
      <td width=69 align="right" style="font-size:12px"><%if(bolShowLabel){%><%=iLineNumber++%><%}%> &nbsp;&nbsp;</td>
      <td width=95 valign=top style="font-size:12px;"><%=strTransDate%></td>
      <td width=108 valign=top style="font-size:12px;"><%if(vRefund.elementAt(iIndex - 2) != null){%><%=(String)vRefund.elementAt(iIndex-2)%><%}else{%>
        <%=(String)vRefund.elementAt(iIndex-3)%>(Refund)
        <%}%></td>
      <td width=80 colspan=2 valign="top" style="font-size:12px;" align="right"><%if(fDebit >= 0f){%> <%=CommonUtil.formatFloat(fDebit,true)%><%}%></td>
      <td width=90 colspan=2 valign="top" style="font-size:12px;" align="right"><%if(fDebit < 0f){%> <%=CommonUtil.formatFloat(fDebit,true)%><%}%></td>
      <td width=82 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fBalance,true)%></td>
      <td width=78 valign="top" style="font-size:12px;">&nbsp;</td>
    </tr>
    <%
	//remove the element here.
	vRefund.removeElementAt(iIndex);vRefund.removeElementAt(iIndex-1);vRefund.removeElementAt(iIndex-2);
	vRefund.removeElementAt(iIndex-3);
}
//dormitory charges
while( (iIndex = vDorm.indexOf((Date)vTimeSch.elementAt(i))) != -1) {
	fDebit = Float.parseFloat((String)vDorm.elementAt(iIndex-1));
	fBalance += fDebit;
%>
   <tr id="row_<%=++iRunningLineNo%>" onClick="printRow(<%=iRunningLineNo%>);" class="nav" onMouseOver="navRollOver('row_<%=iRunningLineNo%>', 'on')" onMouseOut="navRollOver('row_<%=iRunningLineNo%>', 'off')">
      <td width=69 align="right" style="font-size:12px"><%if(bolShowLabel){%><%=iLineNumber++%><%}%> &nbsp;&nbsp;</td>
      <td width=95 valign=top style="font-size:12px;"><%=strTransDate%></td>
      <td width=108 valign=top style="font-size:12px;"><%=(String)vDorm.elementAt(iIndex-2)%></td>
      <td width=80 colspan=2 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fDebit,true)%></td>
      <td width=90 colspan=2 valign="top" style="font-size:12px;">&nbsp;</td>
      <td width=82 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fBalance,true)%></td>
      <td width=78 valign="top" style="font-size:12px;">&nbsp;</td>
    </tr>
    <%
	//remove the element here.
	vDorm.removeElementAt(iIndex);vDorm.removeElementAt(iIndex-1);vDorm.removeElementAt(iIndex-2);
}

//Other school fees/fine/school facility fee charges(except dormitory)
while( (iIndex = vOthSchFine.indexOf((Date)vTimeSch.elementAt(i))) != -1) {
	fDebit = Float.parseFloat((String)vOthSchFine.elementAt(iIndex-1));
	fBalance += fDebit;
%>
   <tr id="row_<%=++iRunningLineNo%>" onClick="printRow(<%=iRunningLineNo%>);" class="nav" onMouseOver="navRollOver('row_<%=iRunningLineNo%>', 'on')" onMouseOut="navRollOver('row_<%=iRunningLineNo%>', 'off')">
      <td width=69 align="right" style="font-size:12px"><%if(bolShowLabel){%><%=iLineNumber++%><%}%> &nbsp;&nbsp;</td>
      <td width=95 valign=top style="font-size:12px;"><%=strTransDate%></td>
      <td width=108 valign=top style="font-size:12px;">OC</td>
      <td width=80 colspan=2 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fDebit,true)%></td>
      <td width=90 colspan=2 valign="top" style="font-size:12px;">&nbsp;</td>
      <td width=82 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fBalance,true)%></td>
      <td width=78 valign="top" style="font-size:12px;">&nbsp;</td>
    </tr>
    <%
	//remove the element here.
	vOthSchFine.removeElementAt(iIndex);vOthSchFine.removeElementAt(iIndex-1);vOthSchFine.removeElementAt(iIndex-2);
}

//vPayment goes here, ;-)
while( (iIndex = vPayment.indexOf((Date)vTimeSch.elementAt(i))) != -1) {
	fCredit = Float.parseFloat((String)vPayment.elementAt(iIndex-2));
	fBalance -= fCredit;
strTemp = WI.getStrValue(vPayment.elementAt(iIndex+1));
iIndexOf = strTemp.indexOf(" Enrollment/downpayment");
if(iIndexOf != -1)
	strTemp = strTemp.substring(0,iIndexOf) + " - DP";
iIndexOf =  strTemp.indexOf(" - Cash");
if(iIndexOf != -1)
	strTemp = strTemp.substring(0,iIndexOf);
iIndexOf =  strTemp.indexOf(" - Check");
if(iIndexOf != -1)
	strTemp = strTemp.substring(0,iIndexOf);
iIndexOf =  strTemp.indexOf(" - SD");
if(iIndexOf != -1)
	strTemp = strTemp.substring(0,iIndexOf);
iIndexOf =  strTemp.indexOf(" Refunded");
if(iIndexOf != -1)
	strTemp = strTemp.substring(0,iIndexOf);
iIndexOf =  strTemp.indexOf(" Refund Transfered");
if(iIndexOf != -1)
	strTemp = strTemp.substring(0,iIndexOf);

if(fCredit < 0d)
	strTemp = "DM";
else if(vPayment.elementAt(iIndex-1) == null) //credit memo
	strTemp = "CM";
	
%>
   <tr id="row_<%=++iRunningLineNo%>" onClick="printRow(<%=iRunningLineNo%>);" class="nav" onMouseOver="navRollOver('row_<%=iRunningLineNo%>', 'on')" onMouseOut="navRollOver('row_<%=iRunningLineNo%>', 'off')">
      <td width=69 align="right" style="font-size:12px"><%if(bolShowLabel){%><%=iLineNumber++%><%}%> &nbsp;&nbsp;</td>
      <td width=95 valign=top style="font-size:12px;"><%=strTransDate%></td>
      <td width=108 valign=top style="font-size:12px;"><%=WI.getStrValue(vPayment.elementAt(iIndex-1))%> <%=strTemp%></td>
      <td width=80 colspan=2 valign="top" style="font-size:12px;" align="right">
	  <%//show only the refunds in debit column.
	  if(fCredit < 0d || (vPayment.elementAt(iIndex+1) != null && ((String)vPayment.elementAt(iIndex+1)).startsWith(" Refunded")) ){%>
	  <%=CommonUtil.formatFloat(-1 * fCredit,true)%><%}%>	  </td>
      <td width=90 colspan=2 valign="top" style="font-size:12px;" align="right">
	  <%if(fCredit >= 0d && (vPayment.elementAt(iIndex+1) == null || !((String)vPayment.elementAt(iIndex+1)).startsWith(" Refunded")) ){%>
	  <%=CommonUtil.formatFloat(fCredit,true)%><%}%>	  </td>
      <td width=82 valign="top" style="font-size:12px;" align="right"><%=CommonUtil.formatFloat(fBalance,true)%></td>
      <td width=78 valign="top" style="font-size:12px;" align="right"><%=(String)vPayment.elementAt(iIndex + 3)%></td>
    </tr>
    <%
//remove the element here.
vPayment.removeElementAt(iIndex+3);
vPayment.removeElementAt(iIndex+2);
vPayment.removeElementAt(iIndex+1);
vPayment.removeElementAt(iIndex);
vPayment.removeElementAt(iIndex-1);
vPayment.removeElementAt(iIndex-2);
}%>
    
<%
}//end of for loop.%>




<!--2002-1157-->







<%//end of for loop..
}///end of if(vTimeSch != null && vTimeSch.size() > 0){
%>	
	
    <tr height=0>
      <td width=69 style='border:none'></td>
      <td width=95 style='border:none'></td>
      <td width=108 style='border:none'></td>
      <td width=62 style='border:none'></td>
      <td width=19 style='border:none'></td>
      <td width=29 style='border:none'></td>
      <td width=61 style='border:none'></td>
      <td width=82 style='border:none'></td>
      <td width=78 style='border:none'></td>
    </tr>
  </table>
<input type="hidden" name="print_clicked">
<input type="hidden" name="max_rows" value="<%=iRunningLineNo%>">
</form>
</body>
</html>
